title:            Variegated
tagline:          Mostly Java
description:      A collection of articles on programming, without an overall theme if I can help it.
url: http://blog.anvard.org

owner:
  name:           Alan Hohn
  avatar:         avatar.png
  bio:            "Lockheed Martin Fellow"
  linkedin:       pub/alan-hohn/27/b35/5a3
  github:         alanhohn
  googleplus:     "+AlanHohn"

links:
  - title: Articles
    url: /articles
  - title: Feed
    url: /feed.xml
  - title: About
    url: /about

timezone:    America/Chicago
future:      true
highlights:  true
markdown:    kramdown
exclude:     [new-post, backup-files]

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  syntax_highlighter_opts:
    line_numbers:
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class
